### ISSUE TITLE
[BUG][UX][Tracker] Active Layer Focus shortcuts working with inverted order

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#1015]
### --Issue Summary--
In the past Pencil and Pencil2d had an inverse layer order where the top layer was "at the bottom" of the stack and the bottom layer was "at the top" of the stack. This was changed a few years ago, however there still seems to be some left overs from the previous behaviour.

- [ ] **[UX]** The issue is that using the hard-coded shortcuts UP ARROW and DOWN ARROW, will change the active layer focus in the same manner as before, that is, pressing UP ARROW will move the focus DOWN, and viceversa.
- [ ] **[Request]** I'd also like to propose to allow the shortcuts to CYCLE through the layers, that is pressing UP ARROW or DOWN ARROW would jump to the top or bottom layer respectively, once it reaches the end of the layer list / array.
- [ ] **[Request]** Also would like to suggest allowing for that command to be overridden / modifiable in the shortcuts window.

### --Expected Results--
Pressing UP ARROW should change the active layer focus UPWARDS, and pressing DOWN ARROW should change the active layer focus DOWNWARDS

### --Steps to reproduce--
1. Open Pencil2D
2. Default Active layer would be the Bitmap layer. Press the UP ARROW.
3. Note that the current active layer is the vector layer.
4. Press the DOWN ARROW. You'll go back to the Bitmap layer.

### --System Information--
+ Pencil2D Version:
Version: 0.6.1.1
commit: c7803d0f761dabb71da6ecdb95f34b05a2b7a71a
date: 2018-07-05_20:03:27
Development build
Operating System: Windows 7 SP 1 (6.1)
CPU Architecture: x86_64

**Comment by TheNiteCoder** [comment]
`void Layer::cycleLayers()
{
    //I didn't know how to set the central widget to a layer otherwise I would include code for this

}

void Layer::createCycleActions()
{
    cycleUpwards = new QAction; //this creates a action
    cycleUpwards->setShortcut(QKeySequence(Qt::Key_Up)); //sets the shortcut to the up arrow
    connect(cycleUpwards, &QAction::triggered, this, &Layer::cycleLayers); //if triggered it cycles  to the 
                                                                                                                      //next layer

    cycleDownwards = new QAction; //same deal just no function created because I don't know how to set 
                                                        //a layer
    cycleDownwards->setShortcut(QKeySequence(Qt::Key_Down));
    connect(cycleDownwards, &QAction::triggered, this, &Layer::cycleLayers);

}`

**Comment by CandyFace** [comment]
@TheNiteCoder 
The section that controls whether to select the next or previous layer is here:

```c++

void LayerManager::gotoNextLayer()
{
    if (editor()->currentLayerIndex() < object()->getLayerCount() - 1)
    {
        editor()->setCurrentLayerIndex(editor()->currentLayerIndex() -1);
        Q_EMIT currentLayerChanged(editor()->currentLayerIndex());
    }
}

void LayerManager::gotoPreviouslayer()
{
    if (editor()->currentLayerIndex() > 0)
    {
        editor()->setCurrentLayerIndex(editor()->currentLayerIndex() + 1);
        Q_EMIT currentLayerChanged(editor()->currentLayerIndex());
    }
}

**Comment by chchwy** [comment]
As CandyFace said, the cycling function should go to `LayerManager` rather than `Layer`.

**Comment by Jose-Moreno** [comment]
Even though the main issue was fixed I'll re-issue the unfulfilled enhancement requests to improve the user experience in the future.
