### ISSUE TITLE
[Tracker] Keyboard Shortcuts

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#1016]
### --Issue Summary--
So I'm making this tracker to have a list of all the "hidden" / hard-coded / undocumented / un-existent keyboard shortcuts for different commands. 

Ideally we should be able to modify most of them and expose them under the shortcuts list, others need to be implemented since they don't exist. Some of them are really difficult to find for a regular user but thanks to @Kaikogf there's a small compilation list of these on the forum from 2015.

[LMB: Left Mouse Button | MMB: Middle Mouse Button | RMB: Right Mouse Button]

## Add Shortcuts for Existing Functionality
_It is assumed that once implemented these will be added to the shortcut list as well_

- [ ] Onion-Skin NEXT Tint
- [ ] Onion-Skin PREV Tint
- [ ] Relative/ Absolute Onion Skin (Toggle match frames or keyframes)
- [ ] Drawing Tools Brush Size (Recommended +/-, Shift + [ & Shift + ])
- [ ] Brush Tools / Enable Quick Sizing Toggle
- [ ] Lock Windows
- [ ] Toggle Playback Range
- [ ] Toggle Sound ON / OFF
- [ ] Selection Flip X
- [ ] Selection Flip Y
- [ ] Show Invisible Lines (Vector)
- [ ] Show Outlines Only (Vector)
- [ ] Toggle Visibility Switch (Pressing the same shortcut would CYCLE through Visible: Opaque Active / Visible: Opaque All / Visible: Solo Active Layer
- [ ] Toggle Layer Visibility ON / OFF

## Add Shortcuts for up-coming functionality [Discussion]
- [ ] Light Table Toggle Switch: This shortcut would enable / disable BOTH Onion Skin  [PREV / NEXT] toggles at the same time; the logic would be =>

|  P/N Switch  |      N OFF     |       N ON      |
|:-----:|:--------------:|:---------------:|
| P OFF | Toggle Both ON |  Toggle Both ON |
|  P ON | Toggle Both ON | Toggle Both OFF |
- [ ] Change Active Layer Order UP & DOWN
- [ ] Pop-up Colour Palette (This was removed, but the feature should be brought back and would require a shortcut)
- [ ] Enable Multi-Layer Onion Skin

## Enable modification in preferences shortcuts list
- [ ] Quick Eraser (Ctrl + Shift)
- [ ] Brush Tools / Quick Sizing (Shift + Drag LMB)
- [ ] Quick Eyedropper (Alt)
- [ ] Delete Selection Content (Backspace)

## Deprecate
- [ ] Rotate selection content (CTRL + Drag Left/Right) -> This should be replaced by a visual widget.
- [ ] Blur Tool (Alt while using Smudge Tool) -> We should separate this tool or consider it as a preset after MyPaint Lib integration.

## Document
_In the following cases LMB can be exchanged with RMB for most operations. I don't think that's by design though_
- [ ] Zoom In/Out (Ctrl+ Spacebar + Drag Up/Down)(CTRL + MMB + Drag Up/Down)(CTRL + RMB + Drag Up/Down)
- [ ] Rotate View (Spacebar + Alt + LMB) (Alt + MMB + Drag)(Alt + RMB + Drag)
- [ ] Pan ( Spacebar + LMB + Drag) (MMB + Drag) (RMB + Drag)
- [ ] Select/deselect a single frame (LMB)
- [ ] Select range of adjacent drawings (Shift + LMB)
- [ ] Select/deselect individual drawings (Ctrl +LMB)
- [ ] Select all drawings from the last drawing up to the current one (Alt + LMB)
- [ ] Move single / multiple selected drawings (LMB + Drag)
- [ ] Blur Tool (Using Smudge Tool: ALT + LMB)
- [ ] Move Frame Forward (CTRL + .) -> This literally moves the current drawing on the timeline using the playback header.
- [ ] Move Frame Backward (CTRL + ,)
- [ ] Toggle Playback Header / Scrub (Double Click on Playback Scrub / Toggle on preferences)
- [ ] Cycle through Panel / Button Focus (TAB / SHIFT + TAB)
    - Each panel and its elements have a specific order to cycle through each. Current Widget Order is: Timeline > Color Inspector > Color Palette > Display > Options > Tool Box
    - There seems to be a mistake in some of the widget buttons in some panels which will be reported later
- [ ] Change Active Layer Focus ( UP/ DOWN ARROW)
- [ ] Transform tool: Keep Aspect Ratio (While resizing: SHIFT + Drag)

**Comment by Jose-Moreno** [comment]
**Hacktoberfest Developers** 
---
We encourage to consider contributing to the **add shortcuts for existing functionality** and **enable modification in preferences shortcut list** sections.
