### ISSUE TITLE
Hacktoberfest 2018 Tracker

### ISSUE THREAD

**Issue by scribblemaniac** [pencil2d/pencil#1067]
This year I would like to see us make an effort to attract new developers through the Hacktoberfest event. For those not familiar with it, the DigitalOcean, Github, and Twilio are partnering to give out free t-shirts to anyone who makes 5 pull requests to open source projects during the month of October. You may find more details about it here: https://hacktoberfest.digitalocean.com/

People may contribute to our project for Hacktoberfest even if we do not do anything. However there are some things we can do to increase traffic from the event and increase involvement. Here are some small things we can do to participate:
- [x] Use the hacktoberfest label to label issue that would be good for new contributors to work on. @Jose-Moreno has started this, developers please look for issues to tag here: https://docs.google.com/document/d/1gCllMnaUCBTDw544Mzi5dGiHA6WRfMYI5PCNpTYUhTA/edit?pli=1
- [x] Add landing page for hacktoberfest similar to what we did with GSOC the describes how to get involved
- [ ] Add a CONTRIBUTING.md file to our project to describe where our documentation is and what our process for submitting changes is.

Additionally we can take measures to make it easier for people to get started. This is something we should work on anyway, but is particularly important this month. Here are a few ideas of things to improve, but I would love to hear more input on this (particularly from new contributors):
- [ ] Improve documentation. Particularly of the project structure, and inline documentation in a form that doxygen can recognize.
- [ ] Create a list of features that could use user documentation (for part of a manual or video tutorial series perhaps)
- [ ] Create official code style guidelines (see https://github.com/pencil2d/pencil/issues/683)
- [ ] Pull or link discussions from the forums and discord to relevant issues if they exist. This can always be done manually with a copy and paste, but it would be nice if there was some semi-automated way to do this.

**Comment by scribblemaniac** [comment]
Hacktoberfest is over now, thank you to everyone who participated! 🎃 

There are a few tasks that need to be done now that it's over (with assignments):
- [ ] Remove hacktoberfest tags, replacing with good-first-issue where applicable @scribblemaniac 
- [X] Close hacktoberfest milestone @scribblemaniac 
- [X] Make a social media announcement of the ending of Hacktoberfest @Jose-Moreno 
- [ ] Make and publish the hacktoberfest showcase video @Jose-Moreno 

Let me know if there is anything I missed.

After the ramp-down tasks are complete, I am going to close this tracker, however the documentation issues still stand. One of the things I am working on right now is the official code style guidelines. Expect to see some stuff related to that come up in the next month or so.

**Comment by scribblemaniac** [comment]
Post-hacktoberfest tasks complete, closing this now. Glad to see that this event generated at least some activity.
