### ISSUE TITLE
Implement document space rulers + view-only guides (with snapping)

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#1071]
### Issue Summary

I believe having the ability to use custom unit rulers on the document bounds, guides and snapping features would help for precision work.

Additionally the implementation of editor / view-only guides (that is they don't appear when selecting the camera or during export) with the possibility of snapping to the guides.

This isn't the same as using the grid because the grid helps dividing the visual space, however guides are used most often for keeping track of specific elements in the picture. e.g I often use a guide to make an invisible floor line for character walks, normally the stride length for a walk is different between legs and more so between characters so you have to "track" the step contact with guides. 

_Note: Other software have integrated pixel tracking devices to simplify and re-position walks, but I'll leave that for another request._

Feature Implementation:
- [ ] Document vertical and horizontal rulers
    **Ruler Units**
    - [ ] Pixel
    - [ ] Metric
    - [ ] Imperial
- [ ] View Guides (Only visible when editing, not on camera)
- [ ] Guide snapping (particularly for vector objects, but could work for geometric bitmap shapes and selections in general)
