### ISSUE TITLE
Ubuntu 18.10 Appimage Issues

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#1185]
### Issue Summary

I managed to borrow a computer with a dual boot Ubuntu 18.10 version so this will be an issue for these problems to help keep track of them.

Here's what I found:

- [ ] Pressing spacebar does not invoke the pan functionality, instead it changes to the move tool. And sometimes it locks the application unexpectedly.
- [ ] Moving the mouse pointer outside the canvas area will lock the cursor to whatever other cursor icon it grabbed, indefinitely. In my test everytime I was going to pick a tool, the mouse pointer passed on top of panel division so the resize cursor (double arrow) was activated, then it remained locked even when returning to the canvas and drawing. The only way to get out of it is to get the application out of focus by pressing CTRL + TAB and come in again. This is related to #1017 
- [ ] The zoom issue found in #1169 is still **not fixed** in Ubuntu 18.10 even though it was fixed for Windows
- [ ] The tablet input events are not working when using the hand tool on a camera camera layer, I could only move the camera using the mouse.
- [ ] I imported a wav file into a sound layer and it does not recognize the sound length nor does it even attempt to import it. The behavior is that of #1180 and it could be related to #1033 Here's a google drive link to the sound I tested [untitle.wav](https://drive.google.com/open?id=1L9iJFbQMul4yjk3zWM0Wp0TNwwPtiiQd)
- [x] There seems to be no problem with the computation window or the off-pressure stroke terminator related to #677 or reported in this [video](https://www.youtube.com/watch?v=kFzmULZxHwE&feature=youtu.be)

### Expected Results

If someone fixes these issues, I'll check mark each issue once it's solved the next time I test this. So please don't close the issue. The expectation is that all of them should not happen

### Steps to reproduce

Each issue is pretty straightforward and those with related attached issues or links have their respective reproduction steps in said reports and videos.

### System Information
+ Pencil2D Version:
Version: 0.6.2
commit: ab160626bfc8d9acd923570b3373b50ccb7042ab
date: 2019-02-27_00:09:57
Development build
Operating System: Ubuntu 18.10
CPU Architecture: x86_64

**Comment by scribblemaniac** [comment]
I cannot reproduce issues 1, 3, and 4. Concerning issue 3, I do notice that it zooms in a little faster than it zooms out with the hand tool, but there is no abrupt zoom out. Can only reproduce the second issue with a tablet. I can confirm 5 and the cause it is well known but unfortunately not easy to fix.

**Comment by scribblemaniac** [comment]
I have reproduced issue 3 now, it must only occur under certain circumstances.

**Comment by Jose-Moreno** [comment]
[2020] I've tested with the nightly build appimage from september 24th 2020 and most of the issues tracker here seem to have been resolved. The only one that wasn't fully fixed was that of #1017 which i'm reopening with new information.

**Comment by J5lx** [comment]
@Jose-Moreno I believe the cursor issue in AppImages was fixed a while ago. Could you test it again and check whether this issue can be closed?

**Comment by scribblemaniac** [comment]
> Oh that’s just great. I haven’t really seen that happen myself tbh, but then again I was somewhat inactive until recently, so maybe I just haven’t noticed yet. But considering that the root cause for this (or at least for the original issue) was always a bug in Qt, would you mind posting your distro and the version of Qt you’re experiencing that issue with?

It could be something that does not happen with Wayland if that is what you are using. I am currently on Ubuntu 21.04 with Qt 5.15.2. I am not sure if I encountered this with the flatpak 0.6.6 version, or if I encountered it with source builds from master, or both. It's one of those things I don't pay much attention to any more, but I will update next time I catch this happening.
