### ISSUE TITLE
Hacktoberfest 2019 Tracker

### ISSUE THREAD

**Issue by scribblemaniac** [pencil2d/pencil#1263]
It's that time of year again...Hacktoberfest time! All of our developers should be familiar with it from last year (#1067), but I'll recap it again just in case. Hacktoberfest is an event where the company Digital Ocean will send free t-shirts to anyone who contributes 4 PRs within the month of October. More details can be found at: https://hacktoberfest.digitalocean.com/.

Now I know there are not very many of us and we are all busy getting things done for v0.6.5, especially in October when we are trying to release it by. However I think it still important for us to put in the effort to attract potential new contributors through this program. The good news is that we can probably reuse much of the material from last year.

Our main tasks to complete before October in order to prepare for this are to improve documentation for the developers. Here is a list of things I can thing of that should be done, feel free to add your own points or to do any of these things:
- [x] Apply hacktoberfest label to issues that would be good for new contributors to work on. This may involve also creating new issues for unreported bugs. Also add them to a Hacktoberfest milestone. See the good first issue label and the recent google doc on small issues compiled by @Jose-Moreno.
- [x] Create a dedicated page for Hacktoberfest on the official website. It can mostly come from https://www.pencil2d.org/2018/10/hacktoberfest-pencil2d.html with updates for this year and the new format as necessary.
- [x] Make new announcement on the official news feed and on social media with a link to the dedicated landing page
- [ ] Add a CONTRIBUTING.md file to our project to describe where our documentation is and what our process for submitting changes is.
- [ ] Improve documentation. I think right now the most important thing would be consolidating the documentation and presenting it in a more friendly manner.
- [ ] Create a list of features that could use user documentation (for part of a manual or video tutorial series perhaps). I think this was a big missed opportunity last year as we didn't get organized soon enough to do this. We've talked about how the user manual and quick reference are out of date, well this is a good chance to get some help with that.
- [ ] Create official code style guidelines (see #683). I thought I did something with this after the last Hacktoberfest, but I'll have to look for it.
- [ ] Provide an anonymous feedback form for Hacktoberfest contributors to honestly reflect on their experiences with us.
- [ ] Perhaps I will throw together a short survey for the current developers to see what they do and don't like about developing for Pencil2D and gather some "testimonials" if you will about what it's like in our community.

**Comment by scribblemaniac** [comment]
Closing this now. Of course we welcome documentation improvements at any time including for the incomplete items mentioned here. We will also revisit any incomplete issues from here again as we approach the next Hacktoberfest.
