### ISSUE TITLE
Canvas performance roadmap

### ISSUE THREAD

**Issue by MrStevns** [pencil2d/pencil#1760]
I'll use this issue for keeping tab on my ongoing work in improving painting performance.

The list of changes I have on my roadmap:
- [ ] Only update the dirty portion of the canvas
First step to improve the painting performance on the canvas would be to introduce a blitter and only update what's dirty. The PaintEvent already has this, we just need to use it.

- [ ] Optimize performance for playback by only blitting the bounds of the image.
Optimize painting for only updating the specified region under playback, right now we always assume the view has been changed and therefore updates everything. This can have major impact on performance on a larger working area, because it needs to update the size of the window, even though only a third of the window is dirty.

- [ ] Introduce a tile buffer faster stroke painting, rather than using mBufferImg which relies on allocating a new image when the bounds needs to be updated.
By introducing a tiled surface, we can draw and update only what's a dirty within for example a 64x64 tile. This would be used for painting only, as it's still faster to draw a single pixmap for playing and as a cache.

- [ ] Move onion skin painting out of the preLayerPixmap cache.
Currently the onion skinning is drawn on the PreLayerPixmap in the CanvasPainter, which means that it's being cleared too often. The onion skin only exists on the current layer right now, so we could move it to a separate pixmap, that is only cleared when modifying the current frame.

- [ ] Align the transformation setup between Bitmap and Vector. 
Right now our vector strokes are drawn in local coordinates, where our bitmap strokes are mapped to the canvas transform. This causes us to have to switch between the matrixes in the painter, which ideally shouldn't be necessary. This change will require some work in all the tools and then adjusting the logic in the canvas painter.

**Comment by chchwy** [comment]
Hey @MrStevns thanks for this fabulous roadmap! This is what I have been thinking for years but still not able to finish.

Just a little reminder, please ensure that you run the profiler after you make changes. When working on performance things, programmers sometimes make assumptions about the bottleneck by just looking at code, but it may not have a significant impact on performance.

For the stroke painting mBufferImg issue, I was thinking to make a buffer image which the size is slightly bigger than the current viewable area of the canvas, to avoid the frequent image copy and allocations.

Anyway, I look forward to your improvements!

**Comment by MrStevns** [comment]
> Just a little reminder, please ensure that you run the profiler after you make changes. When working on performance things, programmers sometimes make assumptions about the bottleneck by just looking at code, but it may not have a significant impact on performance.

So far i've been using the time profiler in Instruments for Mac OS, for discovering and verifying my changes, so that should be covered 😄 

> For the stroke painting mBufferImg issue, I was thinking to make a buffer image which the size is slightly bigger than the current viewable area of the canvas, to avoid the frequent image copy and allocations.

I too considered making that change but having worked with a tiled surface via mypaint, I think there are more possibilities going that way. This will also benefit our rasterized vector strokes. I already have a branch with it working and results are promising, but it could still make sense to compare that against having a big BitmapImage which is pre-allocated.
