### ISSUE TITLE
More selection tools

### ISSUE THREAD

**Issue by chchwy** [pencil2d/pencil#18]
We need more selection tools, like a lasso and a polygonal lasso.

**Comment by J5lx** [comment]
Lasso tool issue: #118

**Comment by Jose-Moreno** [comment]
[2020] Let's leave this issue as a tracker for extra selection tools:
_Note: We should open individual issues for each one, once they've been discussed_

- [ ] Freehand / Lasso Selection https://github.com/pencil2d/pencil/issues/118
- [ ] Polygonal Lasso Selection: Similar to the polyline
- [ ] Ellipse Selection
- [ ] Magic Wand / Eyedropper / Threshold value Selection: Clicking on any given RGBA value (included pure transparent values) would select an area  defined by said value on the canvas and current frame
- [ ] Brush Selection (needs discussion): Would work by converting luminance values (B/W) or alpha values into a marching ants selection area.
