### ISSUE TITLE
Improve support for dark themes

### ISSUE THREAD

**Issue by J5lx** [pencil2d/pencil#550]
> **Note:** This issue is about general problems with existing dark theme support on macOS and Linux. For macOS-specific issues, see #1229. For dark mode support on Windows, see [QTBUG-72028](https://bugreports.qt.io/browse/QTBUG-72028).

When using Pencil with a dark theme (in this case [Adapta-Nokto](https://github.com/adapta-project/adapta-gtk-theme) via the gtk style of Qt), there currently are some components that don't adapt properly. Most of this was originally mentioned in https://github.com/pencil2d/pencil/issues/540#issuecomment-253976402 and then simply extracted into this separate issue upon suggestion of @scribblemaniac.

![Pencil with the Adapta-Nokto theme](https://cloud.githubusercontent.com/assets/2063777/19416395/791b87b0-938f-11e6-8a48-d1160efd35ee.png)

These are the issues that I see there right now, in no particular order:
- [x] The main menu bar looks like it has some custom styling overwriting the theme that should be removed, e.g. the text colour is set according to the theme but the background color clearly isn't. Submenus are not affected and look just fine. See #634.
- [x] The "Display" pane apparently uses some kind of custom-made (and therefore unthemed) buttons, which probably should be exchanged with Qt's standard buttons. See #634.
- [x] The contrast in the system information section of the about dialog ranges from bad to completely nonexistent with dark themes, depending on the exact theme. See #1229 for a screenshot.
- [x] The timeline needs support for theming; currently it doesn't adapt at all. Will probably be solved together with #533
- [ ] Some icons contain fragments of white where they transition from colour to transparency, indicating that they were originally designed for light backgrounds. These icons should be edited or remade accordingly. Obvious examples:
  - The move tool
  - The brush tool
  - The playback controls
  - The "Duplicate Frame" button
  - The zoom entries in the View menu
  
  In some other icons those fragments are also present, but barely even noticeable.

  See #603 and #1356.
- [ ] Some icons don't contrast well with the dark background and should be redesigned accordingly. Obvious examples:
  - The select tool
  - The restore and close buttons on each pane

  See #603 and #1356.

Some additional remarks:
- The icon-related might be solved by switching to a monochrome icon theme, which is what most other programs explicitly supporting both light and dark themes do (e.g. MyPaint, Krita, MuseScore). These programs show light icons when using a dark theme and dark icons when using a light theme
- If a user option for switching between a light and a dark theme is desired (as it has been mentioned before), it might be worth to have a look at Krita and/or MuseScore, which are also Qt programs offering this kind of functionality
- For macOS-specific issues, see #1229
- For Windows dark mode support, see [QTBUG-72028](https://bugreports.qt.io/browse/QTBUG-72028)

**Comment by FrostyFurry** [comment]
How did you even get a dark theme? I really want one.

**Comment by J5lx** [comment]
@FrostyFurry Sorry for not responding earlier, I noticed your comment only now. As mentioned very briefly in the OP, I configured Qt (which is the technology that Pencil2D uses for its graphical interface among many, many other things) to hand off the drawing of interface components to another technology called GTK, then in turn I configured GTK to draw the interface using a dark third-party theme (in this case [Adapta-Nokto](https://github.com/adapta-project/adapta-gtk-theme)). This is a very common setup on Linux-based operating systems, however it requires additional software to be present and Pencil2D must be able to use it. Usually this is only the case on Linux-based systems where Pencil2D was provided by the operating system vendor or manually compiled from its source code, since currently none of the official releases that we provide ourselves include the necessary software. It *should* be possible to obtain that software yourself and configure Pencil2D to use it, however doing so will most likely prove to be very difficult and I can’t really help you with that. It has also previously been suggested that we could include a dark theme with Pencil2D by default and make it easy to use, but so far unfortunately no-one has started working on that as far as I know.
